#!/bin/bash
#Created on: 20150302
#Author: Matt Giguere

#help info:
show_help() {
cat << EOF
USAGE: 
    keepNthRow --help --verbose --header -f OUTPUTFILE INPUTFILE

DESCRIPTION:
    Extract every nth row from the input file. If OUTPUT is not
    set, or the verbose argument is set, results will be printed to 
    screen. If no INPUTFILE, or if INPUTFILE is -, read standard input.

    -h | --help     display this help text and exit

    -f | --file     OUTPUTFILE write the result to OUTPUTFILE instead 
                    of standard output

    -v | --verbose  verbose mode. result will be printed to screen 
                    regardless of whether or not the outputfile is
                    specified.

    -n | --numrows  n to keep. For example, setting this to 10 will 
                    write every tenth row from the input file to
                    standard out and/or the outputfile.

    --header        in addition to keeping every nth row, specifying
                    the --header optional argument will keep the 
                    first row. This is useful if the first row 
                    contains the column names. 
EOF
}

#initialize variables:
output_file=""
verbose=0

#Resets in case getopts was used previously.
OPTIND=1

while getopts "h(--help):f:v(verbose):n:header:" opt; do
	case "$opt" in
		h|--help)
				    show_help
					exit 0
					;;
        v|--verbose)
                    verbose=$((verbose+1))
                    ;;


	esac
done

echo "verbose is: "$((verbose))
echo "outputfile is: "$((output_file))
#now shift (or increment) to the next argument:
#shift
