#!/bin/bash
#Created on: 20150302
#Author: Matt Giguere
#`keepNthRow`: An exercise in making a one line command significantly longer.

#help info:
show_help() {
cat << EOF
USAGE: 
    keepNthRow [-hvk] [-f OUTPUTFILE] [INPUTFILE]

DESCRIPTION:
    Extract every nth row from the input file. If OUTPUT is not
    set, or the verbose argument is set, results will be printed to 
    screen. If no INPUTFILE, or if INPUTFILE is -, read standard input.

    -h              help: display this help text and exit

    -f              OUTPUTFILE write the result to OUTPUTFILE instead 
                    of standard output

    -v              verbose mode. result will be printed to screen 
                    regardless of whether or not the outputfile is
                    specified.

    -n              number of rows to keep. For example, setting this 
                    to 10 will write every tenth row from the input 
                    file to standard out and/or the outputfile.

    -k              keep header row in addition to keeping every nth row.
                    specifying the -k optional argument will keep the 
                    first row. This is useful if the first row 
                    contains the column names. 
EOF
}

#initialize variables:
output_file=" "
verbose=0
numrows=0
keephead=0

#Resets in case getopts was used previously.
OPTIND=1

while getopts "hvn:kf:" opt 
do
	case "$opt" in
		h)
				    show_help
					exit 0
					;;
        v)
                    verbose=$((verbose+1))
                    ;;
        f)   
                    output_file="$OPTARG"
                    ;;
        n)
                    numrows="$OPTARG"
                    ;;
        k)
                    keephead=1
                    ;;
	esac
done

#shift the argument to make the input next:
shift "$((OPTIND-1))"
input=$1

if [ $verbose -gt 0 ]; then
    echo "verbose is: "$((verbose))
fi
if [ $((verbose)) -gt 1 ]; then
    echo "outputfile is: "${output_file}
    echo "numrows is: "${numrows}
    echo "keephead: "${keephead}
    echo "input filename: "${input}
fi

cmd="NR % "${numrows}" == 0"
if [ ${keephead} == 1 ]; then
    cmd="NR == 1 || "${cmd}
fi

if [ ${output_file} != " " ]; then
    awk "${cmd}" ${input} > ${output_file}
fi

if [ ${output_file} == " " ] || [ $((verbose)) -gt 0 ]; then
    awk "${cmd}" ${input}
fi


