#!/bin/csh -f

echo "Initiating Calibration script..."
date

set qtz11nr = `exp_times qtz11nr`
set qtz11st =  `exp_times qtz11st`
set qtz11sc =  `exp_times qtz11sc`
set qtz11fb =  `exp_times qtz11fb`

set qtz31nr =  `exp_times qtz31nr`
set qtz31st =   `exp_times qtz31st`
set qtz31sc =   `exp_times qtz31sc`
set qtz44fb =   `exp_times qtz44fb`

set thar11nr = `exp_times thar11nr`
set thar11st = `exp_times thar11st`
set thar11sc = `exp_times thar11sc`
set thar11fb = `exp_times thar11fb`

set thar31nr = `exp_times thar31nr`
set thar31st = `exp_times thar31st`
set thar31sc = `exp_times thar31sc`
set thar44fb = `exp_times thar44fb`

set iod11nr = `exp_times iod11nr`
set iod11st = `exp_times iod11st`
set iod11sc = `exp_times iod11sc`
set iod11fb = `exp_times iod11fb`

set iod31nr = `exp_times iod31nr`
set iod31st = `exp_times iod31st`
set iod31sc = `exp_times iod31sc`
set iod44fb = `exp_times iod44fb`

echo "setting detector size ..."
pan appmacro set_roi FULL

echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast
pan appmacro speed_normal

echo "positioning slicer motor to narrow_slit position ..."
slicer MOVE narrow_slit

set pos = `iodcell get iodine`
if ("$pos[2]" == "OFF" || "$pos[2]" == "OUT") then
        echo "iodine cell already OUT"
else
        echo "moving iodine cell OUT ..."
        iodcell set iodine OUT
endif

CHIRON EXPM SEND THRESHOLD -1 1000 2

set chi_hour = `date "+%H"`

if ($chi_hour <= "6") then
echo "Wow, you started really late!"
set chi_date = `date -d yesterday "+%y%m%d"`
else
set chi_date = `date "+%y%m%d"`
endif

#set chi_date = `ssh ctimac1 date -v -1d "+%y%m%d"`
#echo "chi_date is: "
#echo $chi_date


set chi_dir = /data/$chi_date
echo "chi_dir is: "
echo $chi_dir

mkdir $chi_dir

GUIUPDATE directory $chi_dir

echo "Setting the Basename..."
pan set image.basename 'chi'$chi_date'.'
GUIUPDATE basename
echo "Retrieving the Basename from the CHIRON GUI..."
set chi_base = `pan get image.basename`
echo "The Basename is: "
echo $chi_base

sleep 2

set im_numb = `pan get image.number`
echo "The image number is: "$im_numb
if ($im_numb >= 1300) then 
echo "Now setting the image number to 1000"
pan set image.number 1000
endif

GUIUPDATE imnumber
echo "Retrieving the Starting Sequence # from the CHIRON GUI..."
set obs_start = `pan get image.number`

echo "The starting Observation # is: "
echo $obs_start

#set it so the GUI does not automatically turn the lamps off
#after the end of the sequence
CHIRON2 OPTGUI GUI UPDATE autolamps off

################################################################
################################################################
#                THORIUM ARGON
################################################################
################################################################

######## NARROW Th-Ar ############
echo "Turning the ThAr lamp on..."
lamp set TH-AR on

echo "Setting the exposure time to 2 seconds..."
pan set exptime $thar31nr
GUIUPDATE exptime

sleep 2

echo "Setting the image title..."
pan set image.title "ThAr"
GUIUPDATE title

sleep 2

echo "Setting the base name..."
pan set image.basename $chi_base
GUIUPDATE basename

sleep 2

echo "Setting the image number..."
pan set image.number $obs_start
GUIUPDATE imnumber

sleep 2

echo "Setting the # Exp. ..."
pan set obs.nimages 1
GUIUPDATE nimages

sleep 2

echo "Now setting the observer"
set observer  = `pan get obs.observer`
echo "The observer is: "
echo $observer

#if ($observer == "_NONE_") then 
#   echo "Setting the Observer ... "
#   pan set obs.observer calib_beg
#   GUIUPDATE observer
#endif

echo "Now waiting one moment"
sleep 2


echo "Setting the observation type..."
pan set obs.obstype Calibration
GUIUPDATE obstype
sleep 1

pan set image.comment " "
GUIUPDATE comment
sleep 2

pan dbs set propid Calib STR
GUIUPDATE propid

sleep 2
#sleep 1
#GUIUPDATE obstype Calibration

echo "Setting autowrite to disk on..."
#pan set autowrite on

echo "Setting autoshutter on..."
pan set autoshutter on

echo "Setting the image directory..."
pan set image.directory $chi_dir
pan set image.dir $chi_dir
GUIUPDATE directory
GUIUPDATE dir

echo "setting geometry mode ..."
pan dbs set geom_mode Calib. STR

echo "updating the GUI..."
GUIUPDATE geometry


echo "Now exposing Narrow_slit ThAr..."
pan expose


######## SLIT Th-Ar ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31st

echo "Now exposing Slit ThAr..."
lamp set TH-AR on
pan expose

######## SLICER Th-Ar ############
echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

#This is the same as the previous exposure:
#echo "Setting the exposure time to 2 seconds..."
#dhe set exptime 1000

echo "Now exposing Slicer ThAr..."
lamp set TH-AR on
pan expose

######## Fiber Th-Ar ############
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $thar44fb

echo "Now exposing Fiber ThAr..."
lamp set TH-AR on
pan expose


echo "Turning the ThAr lamp off..."
lamp set TH-AR off


echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

################################################################
################################################################
#                IODINE OBSERVATIONS
################################################################
################################################################

echo "NOW ON TO THE IODINE EXPOSURES..."

echo "Turning the Quartz lamp on..."
lamp set QUARTZ on

echo "Setting the image title..."
pan set image.title "iodine"

echo "Moving the iodine cell IN to place..."
iodcell set iodine IN

######## SLICER iodine ############
echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31sc

echo "Now exposing Slicer iodine..."
pan expose

######## FIBER iodine ############                                                                                    
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod44fb

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1


######## SLIT iodine ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31st

echo "Now exposing Slit iodine..."
pan expose

######## NARROW_SLIT iodine ############
echo "positioning slicer motor to narrow_slit position ..."
slicer MOVE narrow_slit


echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod31nr

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ on
pan expose

################################################################
################################################################
#                QUARTZ EXPOSURES
################################################################
################################################################

echo "NOW ON TO THE QUARTZ EXPOSURES..."

set numflats = 10

echo "Setting the image title..."
pan set image.title "quartz"

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD 8e6 $iod31nr 10

echo "Turning the Quartz lamp on..."
lamp set QUARTZ off
lamp set QUARTZ on

echo "Moving the iodine cell OUT of place..."
iodcell set iodine OUT


######## NARROW_SLIT  QUARTZ  ############
echo "narrow_slit Quartz exposures..."

echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 10
GUIUPDATE nimages

echo "Setting the exposure time to 1 seconds..."
pan set exptime $qtz31nr

echo "Now exposing Narrow Quartz..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD -1 1000 1

######## SLIT  QUARTZ  ############
echo "slit Quartz exposures..."
pan set obs.nimages $numflats
GUIUPDATE nimages

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31st

echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Now exposing SLIT QUARTZ..."
lamp set QUARTZ on
pan expose

######## FIBER  QUARTZ  ############
echo "fiber Quartz exposures..."

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.2 seconds..."
pan set exptime $qtz44fb

echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "Now exposing FIBER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

######## SLICER  QUARTZ  ############
echo "slicer Quartz exposures..."

#echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 15
GUIUPDATE nimages

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

echo "Now exposing SLICER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Turning the Quartz lamp off..."
lamp set QUARTZ off
#CHIRON2 OPTGUI GUI UPDATE autolamps on

################################################################
################################################################
#                THORIUM ARGON
################################################################
################################################################

######## NARROW Th-Ar ############
echo "Turning the ThAr lamp on..."
lamp set TH-AR on

echo "Setting the exposure time to 2 seconds..."
pan set exptime $thar31nr
GUIUPDATE exptime

sleep 2

echo "Setting the image title..."
pan set image.title "ThAr"
GUIUPDATE title

sleep 2

echo "Setting the base name..."
pan set image.basename $chi_base
GUIUPDATE basename

sleep 2

echo "Setting the image number..."
pan set image.number $obs_start
GUIUPDATE imnumber

sleep 2

echo "Setting the # Exp. ..."
pan set obs.nimages 1
GUIUPDATE nimages

sleep 2

echo "Now setting the observer"
set observer  = `pan get obs.observer`
echo "The observer is: "
echo $observer

#if ($observer == "_NONE_") then 
#   echo "Setting the Observer ... "
#   pan set obs.observer calib_beg
#   GUIUPDATE observer
#endif

echo "Now waiting one moment"
sleep 2


echo "Setting the observation type..."
pan set obs.obstype Calibration
GUIUPDATE obstype
sleep 1

pan set image.comment " "
GUIUPDATE comment
sleep 2

pan dbs set propid Calib STR
GUIUPDATE propid

sleep 2
#sleep 1
#GUIUPDATE obstype Calibration

echo "Setting autowrite to disk on..."
#pan set autowrite on

echo "Setting autoshutter on..."
pan set autoshutter on

echo "Setting the image directory..."
pan set image.directory $chi_dir
pan set image.dir $chi_dir
GUIUPDATE directory
GUIUPDATE dir

echo "setting geometry mode ..."
pan dbs set geom_mode Calib. STR

echo "updating the GUI..."
GUIUPDATE geometry


echo "Now exposing Narrow_slit ThAr..."
pan expose


######## SLIT Th-Ar ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31st

echo "Now exposing Slit ThAr..."
lamp set TH-AR on
pan expose

######## SLICER Th-Ar ############
echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

#This is the same as the previous exposure:
#echo "Setting the exposure time to 2 seconds..."
#dhe set exptime 1000

echo "Now exposing Slicer ThAr..."
lamp set TH-AR on
pan expose

######## Fiber Th-Ar ############
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $thar44fb

echo "Now exposing Fiber ThAr..."
lamp set TH-AR on
pan expose


echo "Turning the ThAr lamp off..."
lamp set TH-AR off


echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

################################################################
################################################################
#                IODINE OBSERVATIONS
################################################################
################################################################

echo "NOW ON TO THE IODINE EXPOSURES..."

echo "Turning the Quartz lamp on..."
lamp set QUARTZ on

echo "Setting the image title..."
pan set image.title "iodine"

echo "Moving the iodine cell IN to place..."
iodcell set iodine IN

######## SLICER iodine ############
echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31sc

echo "Now exposing Slicer iodine..."
pan expose

######## FIBER iodine ############                                                                                    
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod44fb

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1


######## SLIT iodine ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31st

echo "Now exposing Slit iodine..."
pan expose

######## NARROW_SLIT iodine ############
echo "positioning slicer motor to narrow_slit position ..."
slicer MOVE narrow_slit


echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod31nr

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ on
pan expose

################################################################
################################################################
#                QUARTZ EXPOSURES
################################################################
################################################################

echo "NOW ON TO THE QUARTZ EXPOSURES..."

set numflats = 10

echo "Setting the image title..."
pan set image.title "quartz"

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD 8e6 $iod31nr 10

echo "Turning the Quartz lamp on..."
lamp set QUARTZ off
lamp set QUARTZ on

echo "Moving the iodine cell OUT of place..."
iodcell set iodine OUT


######## NARROW_SLIT  QUARTZ  ############
echo "narrow_slit Quartz exposures..."

echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 10
GUIUPDATE nimages

echo "Setting the exposure time to 1 seconds..."
pan set exptime $qtz31nr

echo "Now exposing Narrow Quartz..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD -1 1000 1

######## SLIT  QUARTZ  ############
echo "slit Quartz exposures..."
pan set obs.nimages $numflats
GUIUPDATE nimages

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31st

echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Now exposing SLIT QUARTZ..."
lamp set QUARTZ on
pan expose

######## FIBER  QUARTZ  ############
echo "fiber Quartz exposures..."

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.2 seconds..."
pan set exptime $qtz44fb

echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "Now exposing FIBER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

######## SLICER  QUARTZ  ############
echo "slicer Quartz exposures..."

#echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 15
GUIUPDATE nimages

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

echo "Now exposing SLICER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Turning the Quartz lamp off..."
lamp set QUARTZ off
#CHIRON2 OPTGUI GUI UPDATE autolamps on

################################################################
################################################################
#                THORIUM ARGON
################################################################
################################################################

######## NARROW Th-Ar ############
echo "Turning the ThAr lamp on..."
lamp set TH-AR on

echo "Setting the exposure time to 2 seconds..."
pan set exptime $thar31nr
GUIUPDATE exptime

sleep 2

echo "Setting the image title..."
pan set image.title "ThAr"
GUIUPDATE title

sleep 2

echo "Setting the base name..."
pan set image.basename $chi_base
GUIUPDATE basename

sleep 2

echo "Setting the image number..."
pan set image.number $obs_start
GUIUPDATE imnumber

sleep 2

echo "Setting the # Exp. ..."
pan set obs.nimages 1
GUIUPDATE nimages

sleep 2

echo "Now setting the observer"
set observer  = `pan get obs.observer`
echo "The observer is: "
echo $observer

#if ($observer == "_NONE_") then 
#   echo "Setting the Observer ... "
#   pan set obs.observer calib_beg
#   GUIUPDATE observer
#endif

echo "Now waiting one moment"
sleep 2


echo "Setting the observation type..."
pan set obs.obstype Calibration
GUIUPDATE obstype
sleep 1

pan set image.comment " "
GUIUPDATE comment
sleep 2

pan dbs set propid Calib STR
GUIUPDATE propid

sleep 2
#sleep 1
#GUIUPDATE obstype Calibration

echo "Setting autowrite to disk on..."
#pan set autowrite on

echo "Setting autoshutter on..."
pan set autoshutter on

echo "Setting the image directory..."
pan set image.directory $chi_dir
pan set image.dir $chi_dir
GUIUPDATE directory
GUIUPDATE dir

echo "setting geometry mode ..."
pan dbs set geom_mode Calib. STR

echo "updating the GUI..."
GUIUPDATE geometry


echo "Now exposing Narrow_slit ThAr..."
pan expose


######## SLIT Th-Ar ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31st

echo "Now exposing Slit ThAr..."
lamp set TH-AR on
pan expose

######## SLICER Th-Ar ############
echo "Setting the exposure time to 1 seconds..."
pan set exptime $thar31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

#This is the same as the previous exposure:
#echo "Setting the exposure time to 2 seconds..."
#dhe set exptime 1000

echo "Now exposing Slicer ThAr..."
lamp set TH-AR on
pan expose

######## Fiber Th-Ar ############
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $thar44fb

echo "Now exposing Fiber ThAr..."
lamp set TH-AR on
pan expose


echo "Turning the ThAr lamp off..."
lamp set TH-AR off


echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

################################################################
################################################################
#                IODINE OBSERVATIONS
################################################################
################################################################

echo "NOW ON TO THE IODINE EXPOSURES..."

echo "Turning the Quartz lamp on..."
lamp set QUARTZ on

echo "Setting the image title..."
pan set image.title "iodine"

echo "Moving the iodine cell IN to place..."
iodcell set iodine IN

######## SLICER iodine ############
echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31sc

echo "Now exposing Slicer iodine..."
pan expose

######## FIBER iodine ############                                                                                    
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod44fb

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1


######## SLIT iodine ############
echo "positioning slicer motor to slit position ..."
slicer MOVE slit


echo "Setting the exposure time to 2 seconds..."
pan set exptime $iod31st

echo "Now exposing Slit iodine..."
pan expose

######## NARROW_SLIT iodine ############
echo "positioning slicer motor to narrow_slit position ..."
slicer MOVE narrow_slit


echo "Setting the iod31 narrow exposure time..."
pan set exptime $iod31nr

echo "Now exposing narrow_slit iodine..."
lamp set QUARTZ on
pan expose

################################################################
################################################################
#                QUARTZ EXPOSURES
################################################################
################################################################

echo "NOW ON TO THE QUARTZ EXPOSURES..."

set numflats = 10

echo "Setting the image title..."
pan set image.title "quartz"

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD 8e6 $iod31nr 10

echo "Turning the Quartz lamp on..."
lamp set QUARTZ off
lamp set QUARTZ on

echo "Moving the iodine cell OUT of place..."
iodcell set iodine OUT


######## NARROW_SLIT  QUARTZ  ############
echo "narrow_slit Quartz exposures..."

echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 10
GUIUPDATE nimages

echo "Setting the exposure time to 1 seconds..."
pan set exptime $qtz31nr

echo "Now exposing Narrow Quartz..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Setting the exposure meter set point..."
CHIRON EXPM SEND THRESHOLD -1 1000 1

######## SLIT  QUARTZ  ############
echo "slit Quartz exposures..."
pan set obs.nimages $numflats
GUIUPDATE nimages

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31st

echo "positioning slicer motor to slit position ..."
slicer MOVE slit

echo "Now exposing SLIT QUARTZ..."
lamp set QUARTZ on
pan expose

######## FIBER  QUARTZ  ############
echo "fiber Quartz exposures..."

echo "setting detector binning ..."
pan appmacro set_binning 4 4

echo "setting detector speed ..."
#pan appmacro speed_normal

#echo "Setting the # Exp.to 10 ..."
#dhe set obs.numreads 10

echo "Setting the exposure time to 0.2 seconds..."
pan set exptime $qtz44fb

echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber

echo "Now exposing FIBER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "setting detector binning ..."
pan appmacro set_binning 3 1

echo "setting detector speed ..."
#pan appmacro speed_fast

######## SLICER  QUARTZ  ############
echo "slicer Quartz exposures..."

#echo "Setting the # Exp.to 15 ..."
pan set obs.nimages 15
GUIUPDATE nimages

echo "Setting the exposure time to 0.5 seconds..."
pan set exptime $qtz31sc

echo "positioning slicer motor to slicer position ..."
slicer MOVE slicer

echo "Now exposing SLICER QUARTZ..."
lamp set QUARTZ off
lamp set QUARTZ on
pan expose

echo "Turning the Quartz lamp off..."
lamp set QUARTZ off
#CHIRON2 OPTGUI GUI UPDATE autolamps on

################################################################
################################################################
################################################################
################################################################
echo "            REPEAT ALL FOR 1 X 1 BINNING FOR TESTING"
################################################################
################################################################
################################################################
################################################################

#set oneone = 0

#if ($oneone == 1) then 
  echo "setting detector binning ..."
  pan appmacro set_binning 1 1
  
  ################################################################
  ################################################################
  #                THORIUM ARGON
  ################################################################
  ################################################################
  
  echo "Turning the ThAr lamp on..."
  lamp set TH-AR on
  
  echo "Setting the exposure time to 1 seconds..."
  pan set exptime $thar11nr
  GUIUPDATE exptime
  
  sleep 2
  
  echo "Setting the image title..."
  pan set image.title "ThAr"
  GUIUPDATE title
  
  sleep 2
  
  echo "Setting the base name..."
  pan set image.basename $chi_base
  GUIUPDATE basename
  
  sleep 2
  
  #sleep 2
  
  echo "Setting the # Exp. ..."
  pan set obs.nimages 1
  GUIUPDATE nimages
  
  sleep 2
  
  echo "Setting the observation type..."
  pan set obs.obstype Calibration
  GUIUPDATE obstype
  sleep 1
  
  pan set image.comment " "
  GUIUPDATE comment
  sleep 2
  
  pan dbs set propid Calib11 STR
  GUIUPDATE propid
  
  sleep 2
  echo "Setting autowrite to disk on..."
  #pan set autowrite on
  
  echo "Setting autoshutter on..."
  pan set autoshutter on
  
  echo "Setting the image directory..."
  pan set image.directory $chi_dir
  pan set image.dir $chi_dir
  GUIUPDATE directory
  GUIUPDATE dir
  
  echo "setting geometry mode ..."
  pan dbs set geom_mode Calib. STR
  
  echo "updating the GUI..."
  GUIUPDATE geometry
  
  echo "Now exposing Narrow_slit ThAr..."
  pan expose
  
  ######## SLIT Th-Ar ############
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slit
  
  echo "Setting the exposure time to 0.5 seconds..."
  pan set exptime $thar11st
  
  echo "Now exposing Slit ThAr..."
  lamp set TH-AR on
  pan expose
  
  ######## Fiber Th-Ar ############
  echo "positioning slicer motor to fiber position ..."
  slicer MOVE fiber
  
  echo "Setting the exposure time to 0.25 seconds..."
  pan set exptime $thar11fb
  
  echo "Now exposing Fiber ThAr..."
  lamp set TH-AR on
  pan expose
  
  ######## SLICER Th-Ar ############
  echo "positioning slicer motor to slicer position ..."
  slicer MOVE slicer
  
  #This is the same as the previous exposure:
  echo "Setting the slicer 11 exposure time..."
  pan set exptime $thar11sc
  
  echo "Now exposing Slicer ThAr..."
  lamp set TH-AR on
  pan expose
  
  echo "Turning the ThAr lamp off..."
  lamp set TH-AR off
  
  ################################################################
  ################################################################
  #                IODINE OBSERVATIONS
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE IODINE EXPOSURES..."
  
  echo "Turning the Quartz lamp on..."
  lamp set QUARTZ on
  
  echo "Setting the image title..."
  pan set image.title "iodine"
  
  echo "Moving the iodine cell IN to place..."
  iodcell set iodine IN
  
  ######## SLICER iodine ############
  echo "positioning slicer motor to slicer position ..."
  slicer MOVE slicer
  
  echo "Setting the exposure time to 2 seconds..."
  pan set exptime $iod11sc
  
  echo "Now exposing Slicer iodine..."
  pan expose
  
  ######## NARROW_SLIT iodine ############
  echo "positioning slicer motor to narrow_slit position ..."
  slicer MOVE narrow_slit
  
  echo "Setting the exposure time to 2 seconds..."
  pan set exptime $iod11nr
  
  echo "Now exposing narrow_slit iodine..."
  lamp set QUARTZ on
  pan expose
  
  ################################################################
  ################################################################
  #                QUARTZ EXPOSURES
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE QUARTZ EXPOSURES..."
  
  echo "Setting the image title..."
  pan set image.title "quartz"
  
  echo "Turning the Quartz lamp on..."
  lamp set QUARTZ on
  
  echo "Moving the iodine cell OUT of place..."
  iodcell set iodine OUT
  
  ######## NARROW_SLIT  QUARTZ  ############
  echo "narrow_slit Quartz exposures..."
  
  echo "Setting the # Exp.to 15 ..."
  pan set obs.numreads $numflats
  
  echo "Setting the exposure time to 1 seconds..."
  pan set exptime $qtz11nr
  
  echo "Now exposing Narrow Quartz..."
  lamp set QUARTZ on
  pan expose
  
  ######## SLIT  QUARTZ  ############
  echo "slit Quartz exposures..."
  
  #echo "Setting the # Exp.to 10 ..."
  #dhe set obs.numreads 10
  
  echo "Setting the exposure time to 0.5 seconds..."
  pan set exptime $qtz11st
  
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slit
  
  echo "Now exposing SLIT QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
set oneone = 0

if ($oneone == 1) then

  ######## FIBER  QUARTZ  ############
  echo "fiber Quartz exposures..."
  
  echo "Setting the exposure time to 0.35 seconds..."
  pan set exptime $qtz11fb
  
  echo "positioning slicer motor to fiber position ..."
  slicer MOVE fiber
  
  echo "Now exposing FIBER QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
  ######## SLICER  QUARTZ  ############
  echo "slicer Quartz exposures..."
  
  #echo "Setting the # Exp.to 10 ..."
  #dhe set obs.numreads 10
  
  echo "Setting the exposure time to 1 seconds..."
  pan set exptime $qtz11sc
  
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slicer
  
  echo "Now exposing SLICER QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
  echo "Turning the Quartz lamp off..."
  lamp set QUARTZ off
#  CHIRON2 OPTGUI GUI UPDATE autolamps on
 
GUIUPDATE geometry Quick

echo "Finished Calibrations Script"

echo "logmaker, '"$chi_date"', /over" | ssh -tY ctimac1 "cd /mir7/pro ; idl"

echo "Logsheet created"

echo "Ending BoN Calibration script..."
date

