#!/bin/csh -f

echo "Initiating Calibration script..."
date

set qtz11nr = 90000
set qtz11st = 41000
set qtz11sc = 30000
set qtz11fb = 1850

set qtz31nr = 90000
set qtz31st = 41000
set qtz31sc = 30000
set qtz44fb = 1850

set thar11nr = 1300
set thar11st = 650
set thar11sc = 650
set thar11fb = 300

set thar31nr = 1300
set thar31st = 650
set thar31sc = 650
set thar44fb = 300

set iod11nr = 105000
set iod11st = 47000
set iod11sc = 34000
set iod11fb = 2220

set iod31nr = 105000
set iod31st = 47000
set iod31sc = 34000
set iod44fb = 2220

set chi_base = `pan get image.basename`
set chi_date = `ssh ctimac1 date "+%y%m%d"`


set chi_dir = /data/$chi_date
  echo "Setting the base name..."
  pan set image.basename $chi_base
  GUIUPDATE basename
  
  sleep 2
  
  #sleep 2
  
  echo "Setting the # Exp. ..."
  pan set obs.nimages 1
  GUIUPDATE nimages
  
  sleep 2
  
  echo "Setting the observation type..."
  pan set obs.obstype Calibration
  GUIUPDATE obstype
  sleep 1
  
  pan set image.comment " "
  GUIUPDATE comment
  sleep 2
  
  pan dbs set propid Calib11 STR
  GUIUPDATE propid
  
  sleep 2
  echo "Setting autowrite to disk on..."
  #pan set autowrite on
  
  echo "Setting autoshutter on..."
  pan set autoshutter on
  
  echo "Setting the image directory..."
  pan set image.directory $chi_dir
  pan set image.dir $chi_dir
  GUIUPDATE directory
  GUIUPDATE dir
  
  echo "setting geometry mode ..."
  pan dbs set geom_mode Calib. STR
  
  echo "updating the GUI..."
  GUIUPDATE geometry
  
  echo "Now exposing Narrow_slit ThAr..."
  pan expose
  
  ######## SLIT Th-Ar ############
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slit
  
  echo "Setting the exposure time to 0.5 seconds..."
  pan set exptime $thar11st
  
  echo "Now exposing Slit ThAr..."
  lamp set TH-AR on
  pan expose
  
  ######## Fiber Th-Ar ############
  echo "positioning slicer motor to fiber position ..."
  slicer MOVE fiber
  
  echo "Setting the exposure time to 0.25 seconds..."
  pan set exptime $thar11fb
  
  echo "Now exposing Fiber ThAr..."
  lamp set TH-AR on
  pan expose
  
  ######## SLICER Th-Ar ############
  echo "positioning slicer motor to slicer position ..."
  slicer MOVE slicer
  
  #This is the same as the previous exposure:
  echo "Setting the slicer 11 exposure time..."
  pan set exptime $thar11sc
  
  echo "Now exposing Slicer ThAr..."
  lamp set TH-AR on
  pan expose
  
  echo "Turning the ThAr lamp off..."
  lamp set TH-AR off
  
  ################################################################
  ################################################################
  #                IODINE OBSERVATIONS
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE IODINE EXPOSURES..."
  
  echo "Turning the Quartz lamp on..."
  lamp set QUARTZ on
  
  echo "Setting the image title..."
  pan set image.title "iodine"
  
  echo "Moving the iodine cell IN to place..."
  iodcell set iodine IN
  
  ######## SLICER iodine ############
  echo "positioning slicer motor to slicer position ..."
  slicer MOVE slicer
  
  echo "Setting the exposure time to 2 seconds..."
  pan set exptime $iod11sc
  
  echo "Now exposing Slicer iodine..."
  pan expose
  
  ######## NARROW_SLIT iodine ############
  echo "positioning slicer motor to narrow_slit position ..."
  slicer MOVE narrow_slit
  
  echo "Setting the exposure time to 2 seconds..."
  pan set exptime $iod11nr
  
  echo "Now exposing narrow_slit iodine..."
  lamp set QUARTZ on
  pan expose
  
  ################################################################
  ################################################################
  #                QUARTZ EXPOSURES
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE QUARTZ EXPOSURES..."
  
  echo "Setting the image title..."
  pan set image.title "quartz"
  
  echo "Turning the Quartz lamp on..."
  lamp set QUARTZ on
  
  echo "Moving the iodine cell OUT of place..."
  iodcell set iodine OUT
  
  ######## NARROW_SLIT  QUARTZ  ############
  echo "narrow_slit Quartz exposures..."
  
  echo "Setting the # Exp.to 15 ..."
  pan set obs.numreads 9
  
  echo "Setting the exposure time to 1 seconds..."
  pan set exptime $qtz11nr
  
  echo "Now exposing Narrow Quartz..."
  lamp set QUARTZ on
  pan expose
  
  ######## SLIT  QUARTZ  ############
  echo "slit Quartz exposures..."
  
  #echo "Setting the # Exp.to 10 ..."
  #dhe set obs.numreads 10
  
  echo "Setting the exposure time to 0.5 seconds..."
  pan set exptime $qtz11st
  
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slit
  
  echo "Now exposing SLIT QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
set oneone = 0

if ($oneone == 1) then

  ######## FIBER  QUARTZ  ############
  echo "fiber Quartz exposures..."
  
  echo "Setting the exposure time to 0.35 seconds..."
  pan set exptime $qtz11fb
  
  echo "positioning slicer motor to fiber position ..."
  slicer MOVE fiber
  
  echo "Now exposing FIBER QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
  ######## SLICER  QUARTZ  ############
  echo "slicer Quartz exposures..."
  
  #echo "Setting the # Exp.to 10 ..."
  #dhe set obs.numreads 10
  
  echo "Setting the exposure time to 1 seconds..."
  pan set exptime $qtz11sc
  
  echo "positioning slicer motor to slit position ..."
  slicer MOVE slicer
  
  echo "Now exposing SLICER QUARTZ..."
  lamp set QUARTZ on
  pan expose
  
  echo "Turning the Quartz lamp off..."
  lamp set QUARTZ off
#  CHIRON2 OPTGUI GUI UPDATE autolamps on
  
  ################################################################
  ################################################################
  #                BIAS EXPOSURES
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE BIAS EXPOSURES..."
  
  echo "Setting the image title..."
  pan set image.title "bias"
  
  echo "Setting observation type to bias"
  DHE set obs.obstype bias
  
  echo "Setting the exposure time to 0 seconds..."
  pan set exptime 0000
  
  ######## 3 x 1 FAST BIAS  ############
  echo "3 x 1 fast bias exposures..."
  
  echo "Setting the # Exp.to 15 ..."
  pan set obs.numreads 15
  
  echo "Now exposing 3 x 1 fast bias..."
  pan expose
  
  ######## 4 x 4 NORMAL BIAS  ############
  echo "1 x 1 normal bias exposures..."
  
  echo "setting detector speed ..."
  #pan appmacro speed_normal
  
  echo "Now exposing 1 x 1 normal bias..."
  pan expose
  
  echo "setting detector speed ..."
  #pan appmacro speed_fast
  
  ################################################################
  ################################################################
  #                DARK EXPOSURES
  ################################################################
  ################################################################
  
  echo "NOW ON TO THE DARK EXPOSURES..."
  
  echo "Setting the image title..."
  pan set image.title "dark"
  
  echo "Setting observation type to bias"
  DHE set obs.obstype dark
  
  ######## 1 x 1 FAST 90 sec BIAS  ############
  echo "Setting the exposure time to 90 seconds..."
  pan set exptime 90000
  
  echo "1 x 1 fast dark exposures..."
  
  echo "Setting the # Exp.to 5 ..."
  pan set obs.numreads 5
  
  echo "Now exposing 1 x 1 fast darks..."
  pan expose
  
  ######## 1 x 1 FAST 30 sec BIAS  ############
  echo "Setting the exposure time to 30 seconds..."
  pan set exptime 30000
  
  echo "1 x 1 fast dark exposures..."
  
  echo "Setting the # Exp.to 5 ..."
  pan set obs.numreads 5
  
  echo "Now exposing 1 x 1 fast darks..."
  pan expose
  
  ######## 1 x 1 FAST 37 sec BIAS  ############
  echo "Setting the exposure time to 37 seconds..."
  pan set exptime 37000
  
  echo "1 x 1 fast dark exposures..."
  
  echo "Setting the # Exp.to 5 ..."
  pan set obs.numreads 5
  
  echo "Now exposing 1 x 1 fast darks..."
  pan expose
  
  ######## 1 x 1 FAST 12 sec BIAS  ############
  echo "Setting the exposure time to 12 seconds..."
  pan set exptime 12000
  
  echo "1 x 1 fast dark exposures..."
  
  echo "Setting the # Exp.to 5 ..."
  pan set obs.numreads 5
  
  echo "Now exposing 1 x 1 fast darks..."
  pan expose
endif #oneone

################################################################
################################################################
#    CREATE DIRECTORIES AND SYNC CALIBRATION EXPOSURES
################################################################
################################################################

echo "Creating the directory on ctimac1..."
ssh ctimac1 mkdir /mir7/raw/$chi_date

echo "Now syncing the data to ctimac1..."
#rsync -zuva $chi_dir/ ctimac1:/mir7/raw/$chi_date/
#be nicer to the heartbeat
nice +2 rsync -uva $chi_dir/ ctimac1:/mir7/raw/$chi_date/

################################################################
################################################################
#    FINALLY CHANGE TO THE NARROW_I2 SETTINGS
################################################################
################################################################

#echo "setting detector binning ..."
#pan appmacro set_binning 3 1
#
#echo "setting detector speed ..."
#pan appmacro speed_fast
#
#slicer MOVE narrow_slit
#set pos = `CHIRON2 IODCELL get iodine`
#        iodcell set iodine IN
#
#echo "setting geometry mode ..."
#pan dbs set geom_mode Narrow_i2 STR
#GUIUPDATE geometry Narrow_i2
GUIUPDATE geometry Quick

echo "Finished Calibrations Script"

echo "logmaker, '"$chi_date"', /over" | ssh -tY ctimac1 "cd /mir7/pro ; idl"

echo "Logsheet created"

echo "Ending BoN Calibration script..."
date

