#!/bin/csh -f

echo "checking running processes ..."
set tmpfile = "/tmp/calibchk.list"
rm -f $tmpfile
ps awx > $tmpfile
set procid = ""
set procid  = $procid" "`egrep geom_Calib $tmpfile | awk '{print $1}'`
echo $procid
if ($#procid >1 ) then
        echo "another geom_Calib is already running. NOT started"
        exit -1
endif

echo "Now running the calibrations..."

set chi_hour = `date "+%H"`

if ($chi_hour <= "9") then
echo "Wow, you started really late!"
set chi_date = `date -d yesterday "+%y%m%d"`
else
set chi_date = `date "+%y%m%d"`
endif

#set chi_date = `ssh ctimac1 date -v -1d "+%y%m%d"`
#echo $chi_date
set log = ~/apps/CHIRON/bin/calib_logs/${chi_date}_beg.log
GUIUPDATE LOCK
start_viewlog $log
#calib_beg >> $log
sleep 10
GUIUPDATE UNLOCK

echo "logged some output"

echo Output saved to ${chi_date}_beg.log


kill_viewlog $log
