#!/bin/csh -f

echo "Now running the calibrations..."

set chi_hour = `ssh ctimac1 date "+%H"`

if ($chi_hour <= "9") then
echo "Wow, you started really late!"
set chi_date = `ssh ctimac1 date -v -1d "+%y%m%d"`
else
set chi_date = `ssh ctimac1 date "+%y%m%d"`
endif

#set chi_date = `ssh ctimac1 date -v -1d "+%y%m%d"`
#echo $chi_date
set log = ~/apps/CHIRON/bin/calib_logs/${chi_date}_beg.log
start_viewlog $log
calib_beg >> $log

echo "logged some output"

echo Output saved to ${chi_date}_beg.log

ssh ctimac1 mail -s "Log_for_Calibrations_"${chi_date}_beg.log matthew.giguere@gmail.com <  ~/apps/CHIRON/bin/calib_logs/${chi_date}_beg.log

kill_viewlog $log
