#!/bin/csh -f

echo "setting detetcor size ..."
#pan appmacro set_roi 751 1 3250 4112
pan appmacro set_roi FULL
echo "setting detetcor binning ..."
pan appmacro set_binning 1 1
echo "setting detetcor speed ..."
pan appmacro speed_fast
echo "positioning slicer motor to narrow_slit position ..."
slicer MOVE narrow_slit
set pos = `iodcell get iodine`
if ("$pos[2]" == "OFF" || "$pos[2]" == "OUT") then
        echo "iodine cell already OUT"
else
        echo "moving iodine cell OUT ..."
        iodcell set iodine OUT
endif
echo "setting geometry mode ..."
pan dbs set geom_mode Narrow11_iout STR
pan dhe async GUIUPDATE geometry
