#!/bin/csh -f

echo "setting detetcor size ..."
pan appmacro set_roi full
echo "setting detetcor binning ..."
pan appmacro set_binning 4 4
echo "setting detetcor speed ..."
pan appmacro speed_normal
echo "positioning slicer motor to fiber position ..."
slicer MOVE fiber
set pos = `iodcell get iodine`
if ("$pos[2]" == "OFF" || "$pos[2]" == "OUT") then
        echo "iodine cell already OUT"
else
        echo "moving iodine cell OUT ..."
        iodcell set iodine OUT
endif
echo "setting geometry mode ..."
pan dbs set geom_mode Fiber
pan dhe async GUIUPDATE geometry Fiber
